config/routes.rb
Rails.application.routes.draw do
	devise_for :admin_users, ActiveAdmin::Devise.config
	devise_for :users
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# Defines the root path route ("/")
	root :controller => 'index', :action => :index

	# Defines the root path route ("/")
	# root "articles#index"

	resources :heats, param: :slug do
		get 'leaderboard', to: 'leaderboard#index'
		resources :questions, param: :question_number do
			post 'save_submission', to: 'submissions#save_submission'
			get 'preseedfile', to: 'seed#preseedfile'
			get 'seedfile', to: 'seed#seedfile'
			get 'postseedfile', to: 'seed#postseedfile'
		end
	end
end

app/models/question.rb
class Question < ApplicationRecord
		belongs_to :level
		delegate :contest, :to => :level, :allow_nil => false
		has_many :submissions
		has_one_attached :preseed
		validates :preseed, attached: true, content_type: { content_type: ["text/javascript", "application/x-javascript"] }

		has_one_attached :seed
		validates :seed, attached: true, content_type: { content_type: ["text/javascript", "application/x-javascript"] }

		has_one_attached :postseed
		validates :postseed, attached: true, content_type: { content_type: ["text/javascript", "application/x-javascript"] }

		validates :title, :presence => true
		validates :description, :presence => true
		validates :question_number, :presence => true
		validates :score, :presence => true

		def self.ransackable_attributes(auth_object = nil)
					["created_at", "description", "score", "question_number", "id", "level_id", "postseed", "preseed", "seed", "title", "updated_at"]
				end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
		before_action :authenticate_user!

		def show
					
					ActiveStorage::Current.host = request.base_url

					

					@heat = Heat.find_by(:slug => params[:heat_slug])
					if @heat == nil
							redirect_to root_path, flash: {alert: "Heat does not exist."}
					end

					@question = Question.find_by(:question_number => params[:question_number], :level => @heat.level)
					if @question == nil
							redirect_to heat_path(@heat.slug), flash: {alert: "Question does not exist."}
					end
					@preseed = heat_question_preseedfile_path(@heat.slug, @question)+".js"
					@seed = heat_question_seedfile_path(@heat.slug, @question)+".js"
					@postseed = heat_question_postseedfile_path(@heat.slug, @question)+".js"
		end  
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/show.html.erb
<script src="https://unpkg.com/blockly/blockly.min.js"></script>
<script>javascriptGenerator = javascript.javascriptGenerator</script>
<script src="/publicAssets/JS-Interpreter/interpreter.js"></script>
<script src="/publicAssets/JS-Interpreter/acorn.js"></script>
<script defer type="text/javascript" src="<%= @preseed %>"></script>
<script defer type="text/javascript" src="<%= @seed %>"></script>
<script defer type="text/javascript" src="<%= @postseed %>"></script>

<script>window["heat-path"]="<%= heat_path(params[:heat_slug]) %>"</script>

<%= form_with url: heat_question_save_submission_path(:question_question_number => @question.question_number ), id: "submission-form", method: :post do |form| %>
<% end %>



<div class="blockly-env-wrapper">

     <div class="blockly-editor-wrapper" id="blocklyDiv">
     </div>
     <div class="canvas-wrapper" id="canvasDiv">
     </div>

</div>