config/routes.rb
Rails.application.routes.draw do
	devise_for :admin_users, ActiveAdmin::Devise.config
	devise_for :users
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# Defines the root path route ("/")
	root :controller => 'index', :action => :index

	# Defines the root path route ("/")
	# root "articles#index"

	resources :heats, param: :slug do
		get 'leaderboard', to: 'leaderboard#index'
		resources :questions, param: :question_number do
			post 'save_submission', to: 'submissions#save_submission'
			get 'preseedfile', to: 'seed#preseedfile'
			get 'seedfile', to: 'seed#seedfile'
			get 'postseedfile', to: 'seed#postseedfile'
		end
	end
end

app/models/heat.rb
class Heat < ApplicationRecord
		belongs_to :level
		has_many :submissions
		delegate :contest, :to => :level, :allow_nil => false
		def self.ransackable_attributes(auth_object = nil)
			["created_at", "id", "level_id", "name", "slug", "start_time", "updated_at"]
		end

		validates :name, :presence => true
		validates :start_time, :presence => true
		validates :slug, :presence => true, uniqueness: true
end

app/controllers/heats_controller.rb
class HeatsController < ApplicationController
		before_action :authenticate_user!
		def show
					@heat = Heat.find_by(:slug => params[:slug])
					if @heat == nil
							redirect_to root_path, flash: {alert: "Heat does not exist."}
					end
					if (@heat.start_time.to_datetime) > Time.now.to_datetime
						redirect_to root_path, flash: {alert: "Heat has not started."}
					end
		end   
end

app/helpers/heats_helper.rb
module HeatsHelper
end

app/views/heats/show.html.erb
<h1><%= @heat.contest.name %> &mdash; <%= @heat.level.name %></h1>
<h2><%= @heat.name %>
<% if (((@heat.start_time.to_datetime + @heat.level.duration*1.minute) - Time.now.to_datetime)  * 24 * 60 ).to_i < 1 %>
      | This heat has ended.
<% else %>
      | <%= (((@heat.start_time.to_datetime + @heat.level.duration*1.minute) - Time.now.to_datetime)  * 24 * 60 ).to_i %> minutes left
<% end %>



</h2>

<p><%= @heat.contest.about %></p>
<p><%= link_to "Leaderboard", heat_leaderboard_path(:heat_slug => @heat.slug) %></p>

<table>
     <thead>
          <tr>
               <th>No.</th>
               <th>Question</th>
               <th>Max. score</th>
               <th>Status</th>
          </tr>
     </thead>
     <tbody>
          <% @heat.level.questions.each do |q| %>
               <tr>
                    <td><%= q.question_number %></td>
                    <td class="question-title"><%= q.title %></td>
                    <td><%= q.score %></td>
                    <td>

                         <% if Submission.find_by(
                                   :question_id => Question.find_by(
                                        :question_number => q.question_number, 
                                        :level => @heat.level
                                        ).id, 
                                   :heat => @heat,
                                   :user => current_user
                                   ) %>
                              Finished! | <%= link_to "Attempt again >", heat_question_path(@heat.slug, q.question_number), target: "_blank" %>
                         <% else %>
                              <%= link_to "View this question >", heat_question_path(@heat.slug, q.question_number), target: "_blank" %>
                         <% end %>

                    </td>
               </tr>
          <% end %>
     </tbody>
</table>