config/routes.rb
Rails.application.routes.draw do
	devise_for :admin_users, ActiveAdmin::Devise.config
	devise_for :users
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# Defines the root path route ("/")
	root :controller => 'index', :action => :index

	# Defines the root path route ("/")
	# root "articles#index"

	resources :heats, param: :slug do
		get 'leaderboard', to: 'leaderboard#index'
		resources :questions, param: :question_number do
			post 'save_submission', to: 'submissions#save_submission'
			get 'preseedfile', to: 'seed#preseedfile'
			get 'seedfile', to: 'seed#seedfile'
			get 'postseedfile', to: 'seed#postseedfile'
		end
	end
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
		before_action :authenticate_user!
		def index          
			ActiveStorage::Current.host = request.base_url

			@heat = Heat.find_by(:slug => params[:heat_slug])
			if @heat == nil
				redirect_to root_path, flash: {alert: "Heat does not exist."}
			end

			all_submissions = Submission.where(:heat => @heat)

			@aggr_obj=aggregate_all_scores(all_submissions)

			@aggr = []

			@aggr_obj.each { |(key, value)|
				@aggr.append( {name: key, score: value[:score], timescore: value[:timescore]} )
			}		
		end  

		private
		def aggregate_all_scores submissions
			scores = {}
			submissions.each { |submission|
					if scores[submission.user.username] == nil
								scores[submission.user.username] = {
										score: submission.question.score,
										timescore: (((submission.heat.start_time.to_datetime + submission.level.duration*1.minute) - submission.time.to_datetime)  * 24 * 60 * 60).to_i
								}
					else
								scores[submission.user.username][:score] += submission.question.score
								scores[submission.user.username][:timescore] += submission.heat.start_time + submission.level.duration*1.minute - submission.time
					end
			}

			return scores
		end
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/views/leaderboard/index.html.erb
<h1><%= @heat.contest.name %> | <%= @heat.name %> &mdash; <%= @heat.level.name %> | Leaderboard</h1>

<p><%= link_to "< Back to heat", heat_path(@heat.slug) %></p>

<table>
     <thead>
          <tr>
               <th>Rank</th>
               <th>Player</th>
               <th>Score</th>
               <th>Time Score</th>
          </tr>
     </thead>
     <tbody>
          <% @aggr.sort_by { |score| [-score[:score], -score[:timescore]] }.each_with_index do | scoreobj, index | %>
               <tr>
                    <td><%= (index+1).to_s %></td>
                    <td><%= scoreobj[:name] %></td>
                    <td><%= scoreobj[:score].to_s %></td>
                    <td><%= scoreobj[:timescore].to_s %></td>
               </tr>
          <% end %>
     </tbody>
</table>